// <auto-generated />
using System;
using Infrastructure.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.DataBase.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20231127174645_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.QuestionAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<long?>("TestQuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestQuestionId");

                    b.ToTable("QuestionAnswers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsCorrect = false,
                            TestQuestionId = 1L,
                            Title = "x=2"
                        },
                        new
                        {
                            Id = 2L,
                            IsCorrect = false,
                            TestQuestionId = 1L,
                            Title = "x=3"
                        },
                        new
                        {
                            Id = 3L,
                            IsCorrect = true,
                            TestQuestionId = 1L,
                            Title = "x=4"
                        },
                        new
                        {
                            Id = 4L,
                            IsCorrect = false,
                            TestQuestionId = 2L,
                            Title = "x+6"
                        },
                        new
                        {
                            Id = 5L,
                            IsCorrect = true,
                            TestQuestionId = 2L,
                            Title = "x+4"
                        },
                        new
                        {
                            Id = 6L,
                            IsCorrect = false,
                            TestQuestionId = 2L,
                            Title = "x+4"
                        },
                        new
                        {
                            Id = 7L,
                            IsCorrect = true,
                            TestQuestionId = 3L,
                            Title = "(x−2)(x−3)"
                        },
                        new
                        {
                            Id = 8L,
                            IsCorrect = false,
                            TestQuestionId = 3L,
                            Title = "(x−1)(x−6)"
                        },
                        new
                        {
                            Id = 9L,
                            IsCorrect = false,
                            TestQuestionId = 3L,
                            Title = "(x−2)(x−4)"
                        },
                        new
                        {
                            Id = 10L,
                            IsCorrect = true,
                            TestQuestionId = 4L,
                            Title = "x>2"
                        },
                        new
                        {
                            Id = 11L,
                            IsCorrect = false,
                            TestQuestionId = 4L,
                            Title = "x<2"
                        },
                        new
                        {
                            Id = 12L,
                            IsCorrect = false,
                            TestQuestionId = 4L,
                            Title = "x<3"
                        },
                        new
                        {
                            Id = 13L,
                            IsCorrect = false,
                            TestQuestionId = 5L,
                            Title = "25"
                        },
                        new
                        {
                            Id = 14L,
                            IsCorrect = false,
                            TestQuestionId = 5L,
                            Title = "36"
                        },
                        new
                        {
                            Id = 15L,
                            IsCorrect = true,
                            TestQuestionId = 5L,
                            Title = "16"
                        });
                });

            modelBuilder.Entity("Domain.Models.Test", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Desription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = 2,
                            Desription = "The test provided by harvard to deeply test your math knowledge",
                            Title = "Algebra Harvard testing",
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Domain.Models.TestQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("TestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            TestId = 1L,
                            Title = "2x+5=11:"
                        },
                        new
                        {
                            Id = 2L,
                            TestId = 1L,
                            Title = "Simplify the expression 3(x+2)−2x:"
                        },
                        new
                        {
                            Id = 3L,
                            TestId = 1L,
                            Title = "Factorize the quadratic expression x^2−5x+6:"
                        },
                        new
                        {
                            Id = 4L,
                            TestId = 1L,
                            Title = "Solve the inequality: 3x+7>1:"
                        },
                        new
                        {
                            Id = 5L,
                            TestId = 1L,
                            Title = "Evaluate the expression 4a^2−2ab+b^2 when a=3 and b=2:"
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            Password = "password123",
                            SecondName = "Doe"
                        });
                });

            modelBuilder.Entity("Domain.Models.QuestionAnswer", b =>
                {
                    b.HasOne("Domain.Models.TestQuestion", "TestQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("TestQuestionId");

                    b.Navigation("TestQuestion");
                });

            modelBuilder.Entity("Domain.Models.Test", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Tests")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.TestQuestion", b =>
                {
                    b.HasOne("Domain.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Domain.Models.Test", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Models.TestQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
